### ISSUE TITLE
JSON Migration

### ISSUE THREAD

**Issue by syoon2** [Summer2023SHY/JDec#55]
## Description

The current system uses a proprietary file format, which has not been flexible. For long-term maintainability, it would be better to migrate the data format to JSON.

### Expected Changes

<s>The current `.hdr` and `.bdy` file format will not be supported in versions 2.0 or above.</s>
Limited support will be available for the `.hdr` and `.bdy` file format.

## Tasks

- [x] Implement JSON-based file format
- [x] Rewrite all I/O code with JSON in mind
- [x] Update automata classes to store data in memory
- [x] Update GUI to use JSON based file format
  - [x] Update file chooser window
